---
- name: dotnet application deployment
  hosts: app
  become: yes
  roles:
    - name: install nop
      role: "roles/nop"
- name: configure mysql db installation
  hosts: db
  become: yes
  roles:
    - name: install mysql
      role: buluma.mysql
      mysql_port: 3306
      mysql_databases:
        - name: nopdb
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: nop
          password: nopnop
          priv: "*.*:ALL"
          update_password: on_create
          mysql_bind_address: "0.0.0.0"
