---
- name: dotnet application deployment
  hosts: app
  become: yes
  tasks:
    - name: install dotnet sdk
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop: "{{ packages }}"
    - name: add nop user
      ansible.builtin.user:
        name: "{{ username }}"
        home: "{{ home_dir }}"
    - name: download nopCommerce
      ansible.builtin.unarchive:
        src: "{{ nop_url }}"
        dest: "{{ home_dir }}"
        remote_src: yes
        owner: "{{ username }}"
    - name: create bin and logs
      ansible.builtin.file:
        owner: "{{ username }}"
        path: "{{ home_dir }}/{{ item }}"
        state: directory
      loop: "{{ folders }}"
    - name: copy the service
      ansible.builtin.template:
        src: nop_service.j2
        dest: /etc/systemd/system/nopCommerce.service
    - name: deamon reload, enable and start
      ansible.builtin.systemd_service:
        name: nopCommerce
        daemon_reload: true
        enabled: yes
        state: started
- name: configure mysql db installation
  hosts: db
  become: yes
  roles:
    - name: install mysql
      role: buluma.mysql
      mysql_port: 3306
      mysql_databases:
        - name: nopdb
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: nop
          password: nopnop
          priv: "*.*:ALL"
          update_password: on_create
          mysql_bind_address: "0.0.0.0"
