---
- name: dotnet application deployment
  hosts: app
  become: yes
  tasks:
    - name: install dotnet sdk
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop: "{{ packages }}"
    - name: add nop user
      ansible.builtin.user:
        name: "{{ username }}"
        home: "{{ home_dir }}"
    - name: download nopCommerce
      ansible.builtin.unarchive:
        src: "{{ nop_url }}"
        dest: "{{ home_dir }}"
        remote_src: yes
        owner: "{{ username }}"